### ISSUE TITLE
Got different number

### ISSUE THREAD

**Issue by iglonator** [WhyNotHugo/python-barcode#49] opened 2019-09-14 00:59 UTC
name = generate('EAN13', '1234567890123', output='barcode_svg')

This gives the barcode of '1234567890128'.
Too spare time, the last number is an eight instead of a three. How is this possible?
Even something simple as '55555555555555' changes the last number to a zero: '55555555555550'.

Why is this happening? I definitely need the last number to work to read the right codes, how to fix this?

I have an 9 digit number which I'd just like to turn into a barcode, I thought of using EAN13, multiplying the number by 1000 and making a string out of it, but while doing this it adds random numbers too the last four digits instead of zero's when a barcode is formed. I really don't get why?

Just checked and found that this problem is the case for EAN13, when using gs1_128 I just get the zero's that were supposed to be there. Anyone knows anything more about this?

**Comment by AlanSwenson** [comment] 2019-09-18 00:13
@iglonator I believe your problem stems from how barcodes work.  The last digit in a EAN13 barcode is a check digit
https://www.gs1.org/services/check-digit-calculator
This digit is calculated so that the barcode scanner knows the barcode was generated correctly.  Therefore an EAN13 actually has 12 digits + a check digit.  So whatever the first 12 numbers you put in are generating the 13th digit.  I think the library could use a flag to tell you that you entered too many digits instead of just ignoring 13+.  It does warn you when the you put in too little digits but for some reason not when there is too many.

**Comment by WhyNotHugo** [comment] 2019-09-18 13:36
>  It does warn you when the you put in too little digits but for some reason not when there is too many.

I agree that this should be a thing. Warning when over max length (where applicable) should also be done.

**Comment by WhyNotHugo** [comment] 2020-12-24 13:03
I believe this is a duplicate of #43.
It's addressed by #98, which is still WIP.

**Closed** 2020-12-24 13:03 UTC
Labels: bug, duplicate, enhancement
